In [1]:
#Importing libraries for the dataset
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier   
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [2]:
dataset=pd.read_csv("Preprocessed_Border.csv")
dataset

,sensor_id,timestamp_hour,motion_intensity,vibration_level,thermal_signature,acoustic_level,object_speed_kmph,distance_m,altitude_m,water_pressure,...,weather_condition_Storm,terrain_type_Mountain,terrain_type_Open Field,terrain_type_Riverbank,sensor_status_Degraded,target_class_Animal,target_class_False Alarm,target_class_Human,target_class_Vehicle,target_class_Water Intrusion
0,1001,15,7.87,77.87,710.60,77.87,7.87,710.60,0.00,0.00,...,False,True,False,False,False,False,False,True,False,False
1,1002,6,4.29,75.29,145.61,74.29,4.29,145.61,0.00,0.00,...,False,False,False,False,False,False,False,True,False,False
2,1003,21,7.11,79.11,302.38,77.11,7.11,302.38,0.00,0.00,...,False,False,True,False,False,False,False,True,False,False
3,1004,1,4.94,75.94,589.96,74.94,4.94,589.96,0.00,0.00,...,False,False,False,False,False,False,False,True,False,False
4,1005,23,5.28,75.28,499.80,75.28,5.28,499.80,0.00,0.00,...,False,True,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
345,1346,6,1.02,61.02,420.29,61.02,1.02,415.29,0.00,0.00,...,False,True,False,False,False,False,True,False,False,False
346,1347,6,1.32,62.32,133.90,61.32,1.32,128.90,0.00,3.05,...,True,False,False,False,False,False,True,False,False,False
347,1348,13,1.84,63.84,368.89,61.84,1.84,363.89,0.00,0.00,...,False,False,True,False,False,False,True,False,False,False
348,1349,14,0.96,60.96,277.58,60.96,0.96,272.58,23.15,0.00,...,False,True,False,False,True,False,True,False,False,False


In [3]:
dataset.isnull().sum()

sensor_id                       0
timestamp_hour                  0
motion_intensity                0
vibration_level                 0
thermal_signature               0
acoustic_level                  0
object_speed_kmph               0
distance_m                      0
altitude_m                      0
water_pressure                  0
signal_noise_ratio              0
weight                          0
route_mode_Ground               0
route_mode_Vehicle Route        0
route_mode_Water Route          0
weather_condition_Fog           0
weather_condition_Rain          0
weather_condition_Storm         0
terrain_type_Mountain           0
terrain_type_Open Field         0
terrain_type_Riverbank          0
sensor_status_Degraded          0
target_class_Animal             0
target_class_False Alarm        0
target_class_Human              0
target_class_Vehicle            0
target_class_Water Intrusion    0
dtype: int64

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
indep_X=dataset[['sensor_id', 'object_speed_kmph', 'weight']]

In [6]:
dep_Y=dataset[['target_class_Animal','target_class_False Alarm','target_class_Human','target_class_Vehicle','target_class_Water Intrusion']].idxmax(axis=1)

In [7]:
X_train,X_test,y_train,y_test=train_test_split(indep_X,dep_Y,test_size=0.3,random_state=0)

In [8]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
classifier = SVC(kernel = 'linear', random_state = 0,probability=True)
classifier.fit(X_train, y_train)

,C,1.0
,kernel,'linear'
,degree,3
,gamma,'scale'
,coef0,0.0
,shrinking,True
,probability,True
,tol,0.001
,cache_size,200
,class_weight,None
,verbose,False


In [10]:
y_pred=classifier.predict(X_test)# Eavluate test set input and predict the values
y_pred

array(['target_class_Human', 'target_class_Human',
       'target_class_Water Intrusion', 'target_class_Human',
       'target_class_Water Intrusion', 'target_class_Vehicle',
       'target_class_Vehicle', 'target_class_Animal',
       'target_class_Animal', 'target_class_Animal',
       'target_class_False Alarm', 'target_class_Human',
       'target_class_Animal', 'target_class_Vehicle',
       'target_class_Animal', 'target_class_Vehicle',
       'target_class_Vehicle', 'target_class_False Alarm',
       'target_class_Animal', 'target_class_Animal',
       'target_class_Animal', 'target_class_Water Intrusion',
       'target_class_Human', 'target_class_Animal',
       'target_class_Vehicle', 'target_class_Human', 'target_class_Human',
       'target_class_Animal', 'target_class_Animal',
       'target_class_Vehicle', 'target_class_Human', 'target_class_Human',
       'target_class_Human', 'target_class_Animal', 'target_class_Human',
       'target_class_Animal', 'target_class_Animal

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[37  0  0  0  0]
 [ 0  8  0  0  0]
 [ 0  0 23  0  0]
 [ 0  0  0 20  0]
 [ 0  0  0  0 17]]


In [12]:
from sklearn.metrics import classification_report
clf_report=classification_report (y_test,y_pred)
print(clf_report)

                              precision    recall  f1-score   support

         target_class_Animal       1.00      1.00      1.00        37
    target_class_False Alarm       1.00      1.00      1.00         8
          target_class_Human       1.00      1.00      1.00        23
        target_class_Vehicle       1.00      1.00      1.00        20
target_class_Water Intrusion       1.00      1.00      1.00        17

                    accuracy                           1.00       105
                   macro avg       1.00      1.00      1.00       105
                weighted avg       1.00      1.00      1.00       105



In [13]:
print(classifier.predict_proba(X_test))

[[8.73507537e-03 3.66763146e-03 9.76155382e-01 6.53939450e-03
  4.90251660e-03]
 [1.31931457e-01 9.74888368e-03 8.35534452e-01 8.14093375e-03
  1.46442744e-02]
 [1.81947526e-01 2.47343622e-02 1.25360599e-02 8.97677971e-03
  7.71805272e-01]
 [8.98617883e-02 8.51430685e-03 8.80991827e-01 7.92718997e-03
  1.27048880e-02]
 [3.59855364e-02 9.00336872e-03 6.60859436e-03 7.68560098e-03
  9.40716900e-01]
 [2.01804132e-02 9.13466486e-03 9.31786705e-03 9.48976358e-01
  1.23906973e-02]
 [2.18558736e-02 1.24386531e-02 1.25143561e-02 9.38189822e-01
  1.50012951e-02]
 [9.30553397e-01 1.65062157e-02 3.09814851e-02 4.66240970e-03
  1.72964922e-02]
 [9.07922177e-01 5.68699762e-03 7.66414526e-02 4.20003036e-03
  5.54934215e-03]
 [8.07708502e-01 1.60829687e-02 5.05455717e-03 5.55664915e-03
  1.65597323e-01]
 [1.57217207e-02 9.41543782e-01 9.37706827e-03 7.93200040e-03
  2.54254282e-02]
 [3.39834189e-01 1.18085801e-02 6.22567035e-01 8.31905015e-03
  1.74711454e-02]
 [9.93142953e-01 5.59183206e-04 6.073377

In [14]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, classifier.predict_proba(X_test), multi_class='ovr')


1.0

In [15]:
import pickle
filename='final_Border.sav'
pickle.dump(classifier,open(filename,'wb'))

In [22]:
import pickle
filename='final_sc_Border.sav'
pickle.dump(sc,open(filename,'wb'))

In [19]:
preinput=sc.transform([[10,20,30]])
preinput

C:\Anaconda\envs\aiml\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-11.42391043,  -0.38383934,  -0.67638443]])

In [20]:
load_model=pickle.load(open('final_Border.sav','rb'))
result=load_model.predict(preinput)
print(result)

['target_class_Human']
