In [1]:
#Importing libraries for the dataset
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier   
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier

In [2]:
dataset=pd.read_csv("v1_Preprocessed_Border.csv")
dataset

,motion_intensity,vibration_level,thermal_signature,acoustic_level,object_speed_kmph,water_pressure,target_class_Aerial Object,target_class_Animal,target_class_False Alarm,target_class_Human,target_class_Vehicle,target_class_Water Intrusion
0,7.87,77.87,710.60,77.87,7.87,0.00,False,False,False,True,False,False
1,4.29,75.29,145.61,74.29,4.29,0.00,False,False,False,True,False,False
2,7.11,79.11,302.38,77.11,7.11,0.00,False,False,False,True,False,False
3,4.94,75.94,589.96,74.94,4.94,0.00,False,False,False,True,False,False
4,5.28,75.28,499.80,75.28,5.28,0.00,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
345,1.02,61.02,420.29,61.02,1.02,0.00,False,False,True,False,False,False
346,1.32,62.32,133.90,61.32,1.32,3.05,False,False,True,False,False,False
347,1.84,63.84,368.89,61.84,1.84,0.00,False,False,True,False,False,False
348,0.96,60.96,277.58,60.96,0.96,0.00,False,False,True,False,False,False


In [3]:
dataset.isnull().sum()

motion_intensity                0
vibration_level                 0
thermal_signature               0
acoustic_level                  0
object_speed_kmph               0
water_pressure                  0
target_class_Aerial Object      0
target_class_Animal             0
target_class_False Alarm        0
target_class_Human              0
target_class_Vehicle            0
target_class_Water Intrusion    0
dtype: int64

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [6]:
indep_X=dataset[['motion_intensity', 'vibration_level', 'object_speed_kmph', 'water_pressure']]

In [7]:
dep_Y=dataset[['target_class_Aerial Object','target_class_Animal','target_class_False Alarm','target_class_Human','target_class_Vehicle','target_class_Water Intrusion']].idxmax(axis=1)

In [8]:
X_train,X_test,y_train,y_test=train_test_split(indep_X,dep_Y,test_size=0.3,random_state=0)

In [9]:
classifier = DecisionTreeClassifier(criterion='gini',splitter='best',min_samples_split=2)
classifier.fit(X_train, y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,None
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [10]:
y_pred=classifier.predict(X_test)# Eavluate test set input and predict the values
y_pred

array(['target_class_Human', 'target_class_Human',
       'target_class_Water Intrusion', 'target_class_Human',
       'target_class_Water Intrusion', 'target_class_Vehicle',
       'target_class_Vehicle', 'target_class_Animal',
       'target_class_Animal', 'target_class_Aerial Object',
       'target_class_False Alarm', 'target_class_Human',
       'target_class_Aerial Object', 'target_class_Vehicle',
       'target_class_Animal', 'target_class_Vehicle',
       'target_class_Vehicle', 'target_class_False Alarm',
       'target_class_Aerial Object', 'target_class_Aerial Object',
       'target_class_Aerial Object', 'target_class_Water Intrusion',
       'target_class_Human', 'target_class_Animal',
       'target_class_Vehicle', 'target_class_Human', 'target_class_Human',
       'target_class_Animal', 'target_class_Animal',
       'target_class_Vehicle', 'target_class_Human', 'target_class_Human',
       'target_class_Human', 'target_class_Animal', 'target_class_Human',
       'target_

In [11]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[20  0  0  0  0  0]
 [ 0 17  0  0  0  0]
 [ 0  0  8  0  0  0]
 [ 0  0  0 23  0  0]
 [ 0  0  0  0 20  0]
 [ 0  0  0  0  0 17]]


In [12]:
from sklearn.metrics import classification_report
clf_report=classification_report (y_test,y_pred)
print(clf_report)

                              precision    recall  f1-score   support

  target_class_Aerial Object       1.00      1.00      1.00        20
         target_class_Animal       1.00      1.00      1.00        17
    target_class_False Alarm       1.00      1.00      1.00         8
          target_class_Human       1.00      1.00      1.00        23
        target_class_Vehicle       1.00      1.00      1.00        20
target_class_Water Intrusion       1.00      1.00      1.00        17

                    accuracy                           1.00       105
                   macro avg       1.00      1.00      1.00       105
                weighted avg       1.00      1.00      1.00       105



In [13]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test, classifier.predict_proba(X_test), multi_class='ovo')


np.float64(1.0)

In [14]:
import pickle
filename='final_Border1.sav'
pickle.dump(classifier,open(filename,'wb'))

In [22]:
load_model=pickle.load(open(filename,'rb'))
result=load_model.predict([[2,72,2,0]])
#indep_X=dataset[['motion_intensity', 'vibration_level', 'object_speed_kmph', 'water_pressure']]
print(result)

['target_class_Human']


C:\Anaconda\envs\aiml\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(
